Ps18790_VoMinhChien_AsmGD2/demo/demo/Controllers/GioHangsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using demo.Models;

namespace demo.Controllers
{
    public class GioHangsController : Controller
    {
        private readonly C4Context _context;

        public GioHangsController(C4Context context)
        {
            _context = context;
        }

        // GET: GioHangs
        public async Task<IActionResult> Index()
        {
            var c4Context = _context.GioHang.Include(g => g.MaKhachHangNavigation);
            return View(await c4Context.ToListAsync());

        }
        //public async Task<IActionResult> hiengiohang()
        //{
            
        //    //return View();
        //}
        // GET: GioHangs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gioHang = await _context.GioHang
                .Include(g => g.MaKhachHangNavigation)
                .FirstOrDefaultAsync(m => m.MaGioHang == id);
            if (gioHang == null)
            {
                return NotFound();
            }

            return View(gioHang);
        }

        // GET: GioHangs/Create
        public IActionResult Create()
        {
            ViewData["MaKhachHang"] = new SelectList(_context.KhachHang, "MaKhachHang", "MaKhachHang");
            return View();
        }

        // POST: GioHangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaGioHang,MaKhachHang,ThanhTien,ThueVat,TongTien,TrangThai")] GioHang gioHang)
        {
            if (ModelState.IsValid)
            {
                _context.Add(gioHang);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaKhachHang"] = new SelectList(_context.KhachHang, "MaKhachHang", "MaKhachHang", gioHang.MaKhachHang);
            return View(gioHang);
        }

        // GET: GioHangs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gioHang = await _context.GioHang.FindAsync(id);
            if (gioHang == null)
            {
                return NotFound();
            }
            ViewData["MaKhachHang"] = new SelectList(_context.KhachHang, "MaKhachHang", "MaKhachHang", gioHang.MaKhachHang);
            return View(gioHang);
        }

        // POST: GioHangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaGioHang,MaKhachHang,ThanhTien,ThueVat,TongTien,TrangThai")] GioHang gioHang)
        {
            if (id != gioHang.MaGioHang)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gioHang);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GioHangExists(gioHang.MaGioHang))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaKhachHang"] = new SelectList(_context.KhachHang, "MaKhachHang", "MaKhachHang", gioHang.MaKhachHang);
            return View(gioHang);
        }

        // GET: GioHangs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gioHang = await _context.GioHang
                .Include(g => g.MaKhachHangNavigation)
                .FirstOrDefaultAsync(m => m.MaGioHang == id);
            if (gioHang == null)
            {
                return NotFound();
            }

            return View(gioHang);
        }

        // POST: GioHangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gioHang = await _context.GioHang.FindAsync(id);
            _context.GioHang.Remove(gioHang);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GioHangExists(int id)
        {
            return _context.GioHang.Any(e => e.MaGioHang == id);
        }
    }
}

Ps18790_VoMinhChien_AsmGD2/demo/demo/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using demo.Models;

namespace demo.Controllers
{
    public class SanPhamsController : Controller
    {
        private readonly C4Context _context;

        public SanPhamsController(C4Context context)
        {
            _context = context;
        }

        // GET: SanPhams
        public async Task<IActionResult> Index()
        {
            var c4Context = _context.SanPham.Include(s => s.MaTheLoaiNavigation);
            return View(await c4Context.ToListAsync());
        }

        // GET: SanPhams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPham
                .Include(s => s.MaTheLoaiNavigation)
                .FirstOrDefaultAsync(m => m.MaSanPham == id);
            if (sanPham == null)
            {
                return NotFound();
            }

            return View(sanPham);
        }

        // GET: SanPhams/Create
        public IActionResult Create()
        {
            ViewData["MaTheLoai"] = new SelectList(_context.TheLoai, "MaTheLoai", "MaTheLoai");
            return View();
        }

        // POST: SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaSanPham,HinhAnh,TenSanPham,GiaSanPham,TinhTrang,MaTheLoai,ThongTin,Khac,Isdelete")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sanPham);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaTheLoai"] = new SelectList(_context.TheLoai, "MaTheLoai", "MaTheLoai", sanPham.MaTheLoai);
            return View(sanPham);
        }

        // GET: SanPhams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPham.FindAsync(id);
            if (sanPham == null)
            {
                return NotFound();
            }
            ViewData["MaTheLoai"] = new SelectList(_context.TheLoai, "MaTheLoai", "MaTheLoai", sanPham.MaTheLoai);
            return View(sanPham);
        }

        // POST: SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaSanPham,HinhAnh,TenSanPham,GiaSanPham,TinhTrang,MaTheLoai,ThongTin,Khac,Isdelete")] SanPham sanPham)
        {
            if (id != sanPham.MaSanPham)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sanPham);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SanPhamExists(sanPham.MaSanPham))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaTheLoai"] = new SelectList(_context.TheLoai, "MaTheLoai", "MaTheLoai", sanPham.MaTheLoai);
            return View(sanPham);
        }

        // GET: SanPhams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPham
                .Include(s => s.MaTheLoaiNavigation)
                .FirstOrDefaultAsync(m => m.MaSanPham == id);
            if (sanPham == null)
            {
                return NotFound();
            }

            return View(sanPham);
        }

        // POST: SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sanPham = await _context.SanPham.FindAsync(id);
            _context.SanPham.Remove(sanPham);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SanPhamExists(int id)
        {
            return _context.SanPham.Any(e => e.MaSanPham == id);
        }
    }
}

Ps18790_VoMinhChien_AsmGD2/demo/demo/Controllers/ShowGioHangController.cs
using demo.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace demo.Controllers
{
    public class ShowGioHangController : Controller
    {
        private readonly C4Context _context;

        public ShowGioHangController(C4Context context)
        {
            _context = context;
        }
        public SanPham Find(int id)
        {
            var a = _context.SanPham.Find(id);
            return a;
        }
        [Route("index")]

        public IActionResult Index()
        {
            var cart = SessionExtensions.GetobjectFromJson<List<Items>>(HttpContext.Session, "cart");
            ViewBag.cart = cart;

            if (cart != null)
            {
                ViewBag.total = cart.Sum(item => double.Parse(item.sp.GiaSanPham) * item.SoLuong);
            }


            return View();
        }
        private int isExist(int id)
        {
            List<Items> cart = SessionExtensions.GetobjectFromJson<List<Items>>(HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].sp.MaSanPham.Equals(id))
                {
                    return i;
                }  
            }
            return -1;
        }
        [Route("buy/{id}")]
        public IActionResult buy(int id)
        {
            if (SessionExtensions.GetobjectFromJson<List<Items>>(HttpContext.Session, "cart") == null)
            {
                List<Items> cart = new List<Items>();
                cart.Add(new Items
                {
                    sp = Find(id),
                    SoLuong = 1
                });
                SessionExtensions.SetobjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                List<Items> cart = SessionExtensions.
                                 GetobjectFromJson<List<Items>>(HttpContext.Session, "cart");
                int index = isExist(id);
                if (index != -1)
                {
                    cart[index].SoLuong++;
                }
                else
                {
                    cart.Add(new Items
                    {
                        sp = Find(id),
                        SoLuong = 1
                    });
                }
                SessionExtensions.SetobjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToAction("Index");

        }
        [Route("remove/{id}")]
        public IActionResult Remove(int id)
        {
            List<Items> cart = SessionExtensions.GetobjectFromJson<List<Items>>(HttpContext.Session, "cart");
            int index = isExist(id);
            cart.RemoveAt(index);
            SessionExtensions.SetobjectAsJson(HttpContext.Session,"cart", cart);
            return RedirectToAction("Index");
        }
    }
}

Ps18790_VoMinhChien_AsmGD2/demo/demo/Controllers/TheLoaisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using demo.Models;

namespace demo.Controllers
{
    public class TheLoaisController : Controller
    {
        private readonly C4Context _context;

        public TheLoaisController(C4Context context)
        {
            _context = context;
        }

        // GET: TheLoais
        public async Task<IActionResult> Index()
        {
            return View(await _context.TheLoai.ToListAsync());
        }

        // GET: TheLoais/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var theLoai = await _context.TheLoai
                .FirstOrDefaultAsync(m => m.MaTheLoai == id);
            if (theLoai == null)
            {
                return NotFound();
            }

            return View(theLoai);
        }

        // GET: TheLoais/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TheLoais/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaTheLoai,TenTheLoai,Isdelete")] TheLoai theLoai)
        {
            if (ModelState.IsValid)
            {
                _context.Add(theLoai);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(theLoai);
        }

        // GET: TheLoais/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var theLoai = await _context.TheLoai.FindAsync(id);
            if (theLoai == null)
            {
                return NotFound();
            }
            return View(theLoai);
        }

        // POST: TheLoais/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaTheLoai,TenTheLoai,Isdelete")] TheLoai theLoai)
        {
            if (id != theLoai.MaTheLoai)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(theLoai);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TheLoaiExists(theLoai.MaTheLoai))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(theLoai);
        }

        // GET: TheLoais/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var theLoai = await _context.TheLoai
                .FirstOrDefaultAsync(m => m.MaTheLoai == id);
            if (theLoai == null)
            {
                return NotFound();
            }

            return View(theLoai);
        }

        // POST: TheLoais/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var theLoai = await _context.TheLoai.FindAsync(id);
            _context.TheLoai.Remove(theLoai);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TheLoaiExists(int id)
        {
            return _context.TheLoai.Any(e => e.MaTheLoai == id);
        }
    }
}

Ps18790_VoMinhChien_AsmGD2/demo/demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - demo</title>
    
      <link rel="stylesheet" href="~/css/ManHinhChinh.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="dinhdang.css" />
    <link rel="stylesheet" href="~/css/site.css" />
     <link rel="stylesheet" href="~/css/tuyet.css" />
     <link rel="stylesheet" href="~/css/StyleSheet.css" />
     
</head>
<body>
    <div class="snowflakes" aria-hidden="true">
  <div class="snowflake">❅</div>
  <div class="snowflake">❆</div>
  <div class="snowflake">❅</div>
  <div class="snowflake">❆</div>
  <div class="snowflake">❅</div>
  <div class="snowflake">❆</div>
  <div class="snowflake">❅</div>
  <div class="snowflake">❆</div>
  <div class="snowflake">❅</div>
  <div class="snowflake">❆</div>
  <div class="snowflake">❅</div>
  <div class="snowflake">❆</div>
  <div class="snowflake">❆</div>
  <div class="snowflake">❆</div>
  </div>

    <header>
        <div class="header-top">
            <h1>
                <a onclick="location.href='@Url.Action("Index", "Home")'">CHIẾN<em> BLACK</em> </a> 
            </h1>

        <div id="menudangky">              
            <a href="#">@Html.ActionLink("Đăng Xuất","giaodien","Dn")<img src=~/Images/dangnhap.png /></a>
            
             @*<button onclick="location.href='@Url.Action("Index", "GioHangControllers")'"><i class="fa fa-shopping-basket" aria-hidden="true"></i> Giỏ Hàng</button>*@
        </div>
        </div>

         <div class ="chuchay">
              <marquee  direction="left" > <b class="hd"> 📣 📢  Mọi Thắc Mắc xin Liên Hệ HotLine : 098.56.2468.5 🧡---------------------------------------------------------🔔Địa chỉ : 473 Nguyễn Tri Phương , Dĩ an , Bình Dương💓</b></marquee>
        </div>

        <div class="container-ef">
          <div class="text"><span>Chào mừng đến với Shop Chúc Bạn Ngày Mới Vui Vẻ</span></div>
        </div>


     @*   <form action="" class="search-bar">
  <input type="search" name="search" pattern=".*\S.*" required>
  <button class="search-btn" type="submit">
    <span>Search</span>
  </button>
</form>*@


        <nav>   
        <ul class="hmenu">
            <li><a href="#">Điện Thoại</a>
            <ul class="sub-menu">
                <li>
                    <a asp-controller ="ShowSanPham" asp-action="Index" asp-route-MaTheLoai ="1">SamSung</a>
                </li>
                    <li ><a asp-controller ="ShowSanPham" asp-action="Index" asp-route-MaTheLoai ="2">LG</a></li>
                    <li><a asp-controller ="ShowSanPham" asp-action="Index" asp-route-MaTheLoai ="3">Iphone</a></li>
                    <li><a asp-controller ="ShowSanPham" asp-action="Index" asp-route-MaTheLoai ="4">Oppo</a></li>
                    <li><a asp-controller ="ShowSanPham" asp-action="Index" asp-route-MaTheLoai ="5">Redmi</a></li>
            </ul></li>
            <li><a href="#">LapTop</a>
                <ul class="sub-menu">
                    <li><a asp-controller ="ShowSanPham" asp-action="Index" asp-route-MaTheLoai ="6">Dell</a></li>
                        <li ><a asp-controller ="ShowSanPham" asp-action="Index" asp-route-MaTheLoai ="7">Lenovo</a></li>
                        <li><a asp-controller ="ShowSanPham" asp-action="Index" asp-route-MaTheLoai ="8">Msi</a></li>
                        <li><a asp-controller ="ShowSanPham" asp-action="Index" asp-route-MaTheLoai ="9">HP</a></li>
                        <li><a asp-controller ="ShowSanPham" asp-action="Index" asp-route-MaTheLoai ="10">Asus</a></li>
                </ul>
            </li>
            <li><a href="#">Máy Tính Bảng</a>
                <ul class="sub-menu">
                    <li><a asp-controller ="ShowSanPham" asp-action="Index" asp-route-MaTheLoai ="11">Asus</a></li>
                    <li><a asp-controller ="ShowSanPham" asp-action="Index" asp-route-MaTheLoai ="12">Dell</a></li>
                    <li><a asp-controller ="ShowSanPham" asp-action="Index" asp-route-MaTheLoai ="13">SamSung</a></li>
                    <li><a asp-controller ="ShowSanPham" asp-action="Index" asp-route-MaTheLoai ="14">Xiaomi</a></li>
                    <li><a asp-controller ="ShowSanPham" asp-action="Index" asp-route-MaTheLoai ="15">Lenovo</a></li>
                    <li><a asp-controller ="ShowSanPham" asp-action="Index" asp-route-MaTheLoai ="16">Masstel</a></li>
                    <li><a asp-controller ="ShowSanPham" asp-action="Index" asp-route-MaTheLoai ="17">Huawei</a></li>
                    

                    
                </ul>
            </li>

            <li><a href="#">Góp ý</a>
                <ul class="sub-menu">
                    <li><a href="https://www.facebook.com/messages/t/100027223480172">Trợ Giúp</a></li>
                    <li><a href="#">phản hồi</a></li>
                </ul>
            </li>
            <li>
                <a asp-controller="ShowGioHang" asp-action="Index">Giỏ Hàng <img  src="~/Images/giohang.png" /></a>
            </li>
        </ul>
    </nav>
    </header>
    
    
    <div class="d-flex">
 
      <article class="flex-grow-1 ">
        @RenderBody()
      </article>

        <aside>
            <div class="thongtin">
                <ul>
                   @*// <li>@Html.ActionLink("Thông Tin","Index","ThongTinControllers")</li>*@
                    <li>@Html.ActionLink("QL Khách Hàng","Index","KhachHangs")</li>
                    <li>@Html.ActionLink("QL Loại Sản Phẩm","Index","TheLoais")</li>
                    <li>@Html.ActionLink("QL  Sản Phẩm","Index","SanPhams")</li>
                   @* <li>@Html.ActionLink("QL  Giỏ Hàng","Index","GioHangs")</li>
                    <li>@Html.ActionLink("QL  Chi Tiết Giỏ Hàng","Index","ChiTietGioHangs")</li>*@
                </ul>
            </div>
        </aside>
    </div>

    <footer>
        Copyright &copy; 2022 Training Studio

        - Designed by <a rel="nofollow" href="https://www.facebook.com/kho.trai.1422" class="tm-text-link" target="_parent">Minh chiến</a>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
   <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>