Ps18790_VoMinhChien_AsmGD2/demo/demo/Models/DangNhap.cs
namespace demo.Models
{
    public class DangNhap
    {
    }
}

Ps18790_VoMinhChien_AsmGD2/demo/demo/Controllers/DNController.cs
using demo.Models;
using demo.TienIch;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace demo.Controllers
{
    public class DNController : Controller
    {
        private readonly C4Context context;

        public DNController(C4Context context)
        {
            this.context = context;
        }
       // [Route("/")]
        public IActionResult Index()
        {
            var user = Session.GetSessionData<KhachHang>(HttpContext.Session, "user");

            ViewBag.user = user;

           return View();
        }
        public IActionResult KhHang()
        {
            var user = Session.GetSessionData<KhachHang>(HttpContext.Session, "user");

            ViewBag.user = user;

            return View();
        }

        [Route("/dangnhap")]
        public IActionResult DangNhap()
        {
            return View();
        }

       [Route("/dangnhap")]
        [HttpPost]
        public async Task<IActionResult> DangNhap(KhachHang user)
        {
            if (ModelState.IsValid)
            {

                var existsEmail = await context.KhachHang
                    .SingleOrDefaultAsync(u => u.Email == user.Email && u.MatKhau == user.MatKhau);

                if (existsEmail != null)
                {

                    Session.SetSessionData(HttpContext.Session, "user", user);

                    TempData["alert"] = Alert.ShowAlert(Alerts.Success, "Đăng nhập thành công");

                    Session.SetSessionData(HttpContext.Session, "user", user);

                    TempData["alert"] = Alert.ShowAlert(Alerts.Success, "Đăng nhập thành công");
                    if (existsEmail.VaiTro == 0)
                    {
                        return RedirectToAction("KhHang");
                    }
                    else if (existsEmail.VaiTro == 1)
                    {
                        return RedirectToAction("index");
                    }
                }

                TempData["alert"] = Alert.ShowAlert(Alerts.Danger, "Email hoặc mật khẩu không chính xác");

                return View(user);
            }

            return View(user);
        }

        [Route("/dangky")]
        public IActionResult DangKy()
        {
            return View();
        }

       [Route("/dangky")]
        [HttpPost]
        public async Task<IActionResult> DangKy(KhachHang user)
        {
            if (ModelState.IsValid)
            {

                var existsEmail = await context.KhachHang
                    .SingleOrDefaultAsync(u => u.Email == user.Email);

                if (existsEmail == null)
                {
                    var newUser = new KhachHang
                    {
                        Email = user.Email,
                        MatKhau = user.MatKhau
                    };

                    await context.KhachHang.AddAsync(newUser);
                    await context.SaveChangesAsync();

                    TempData["alert"] = Alert
                        .ShowAlert(Alerts.Success, "Đăng ký thành công");

                    return RedirectToAction("DangNhap");
                }


                TempData["alert"] = Alert
                        .ShowAlert(Alerts.Danger, "Email đã tồn tại");

                return View(user);
            }

            return View(user);
        }
        public IActionResult giaodien()
        {
            return View();
        }
    }

}

Ps18790_VoMinhChien_AsmGD2/demo/demo/Controllers/DangNhapController.cs
using Microsoft.AspNetCore.Mvc;

namespace demo.Controllers
{
    public class DangNhapController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Ps18790_VoMinhChien_AsmGD2/demo/demo/Views/DN/DangKy.cshtml
@model demo.Models.KhachHang

<div>
    @Html.Raw(TempData["alert"])
</div>
<style>
     .form-control{
        width:400px;
    }
    .text-center{
        text-align:center;
        background-color:pink;
    width:800px;
    height:50px;
    }
    .main-banner {
    position: relative;
   
}
.ngoai{
    margin-left:30%;
}
h1{
    text-align:center
}

.main-banner{
    background-color:yellow;
    width:800px;
    height:400px;
    margin-top:-50px;
}
</style >
<div class="ngoai">
    <div class="text-center">
    <button>  @Html.ActionLink("Trang Chủ","giaodien","Dn")</button>
    <button >@Html.ActionLink("Đăng Nhập","DangNhap","Dn")</button>
</div>
<div class="main-banner">
<form style="width: 500px; margin-inline: auto;"
      asp-controller="DN" asp-action="DangKy"
      method="post" enctype="multipart/form-data">
    <h1>Đăng ký</h1>

    <div class="form-group">
        <label asp-for="Email">Email</label><br /><br />
        <input type="email" class="form-control" asp-for="Email" autofocus>
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <br /><br />
    <div class="form-group">
        <label asp-for="MatKhau">Mật khẩu</label><br /><br />
        <input type="MatKhau" class="form-control" asp-for="MatKhau">
        <span asp-validation-for="MatKhau" class="text-danger"></span>
    </div>
    <br /><br />
    <button type="submit" class="btn btn-primary">Đăng ký</button>
</form>


</div>
</div>

Ps18790_VoMinhChien_AsmGD2/demo/demo/Views/DN/DangNhap.cshtml
@model demo.Models.KhachHang

<div>
    @Html.Raw(TempData["alert"])
</div>
<style>
    .form-control{
        width:400px;
    }
    .text-center{
        text-align:center;
        background-color:pink;
    width:800px;
    height:50px;
    }
    .main-banner {
    position: relative;
   
}
.ngoai{
    margin-left:30%;
}
h1{
    text-align:center
}

.main-banner{
    background-color:yellow;
    width:800px;
    height:400px;
    margin-top:-50px;
}

</style>
<div class="ngoai">  
<div class="text-center">
    <button>  @Html.ActionLink("Trang Chủ","giaodien","Dn")</button>
    <button>@Html.ActionLink("Đăng Ký","DangKy","Dn")</button>
</div>
<div class="main-banner">
     

<form 
      style="width: 500px; margin-inline: auto;"
      asp-controller="DN" asp-action="DangNhap"
      method="post" enctype="multipart/form-data">
    <h1>Đăng nhập</h1>
    
    <div class="form-group">
        <label asp-for="Email">Email</label><br /><br />
        <input type="email" class="form-control" asp-for="Email" autofocus>
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        <label asp-for="MatKhau">Mật khẩu</label><br /><br />
        <input type="MatKhau" class="form-control" asp-for="MatKhau">
        <span asp-validation-for="MatKhau" class="text-danger"></span>
    </div>
    <br /><br />
    <button type="submit" class="btn btn-primary">Đăng nhập</button>
</form>
</div></div>

Ps18790_VoMinhChien_AsmGD2/demo/demo/Views/DN/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@{
    
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>*@
<img style ="width:100%" src="~/Images/dt.jpg"/>

Ps18790_VoMinhChien_AsmGD2/demo/demo/Views/DN/KhHang.cshtml
<a> đây là Khách Hàng</a>

Ps18790_VoMinhChien_AsmGD2/demo/demo/Views/DN/giaodien.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">
    <meta charset="utf-8" />
    <title>chien electronice device</title>
    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="css/font-awesome.css">

    <link rel="stylesheet" href="css/templatemo-training-studio.css">
</head>
<body>

    <!-- ***** Preloader Start ***** -->
    <!--<div id="js-preloader" class="js-preloader">
        <div class="preloader-inner">
            <span class="dot"></span>
            <div class="dots">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>b
    </div>-->
    <!-- ***** Preloader End ***** -->
    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                         <!--***** Logo Start *****--> 
                        <a style="margin-left:100px;"  onclick="location.href='@Url.Action("Index", "GiaoDienNgoaiControllers")'" class="logo">CHIEN<em> BLACK</em></a>
                         <!--***** Logo End ***** 
                         ***** Menu Start *****--> 

                        <ul class="nav">
                           
                           @* <li class="main-button"> @Html.ActionLink("Đăng Nhập","Index","DangNhap")</li>*@
                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                         <!--***** Menu End *****--> 
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->
    <!-- ***** Main Banner Area Start ***** -->
    <div class="main-banner" id="top">
        <!--<video autoplay muted id="bg-video">
            <source src="/Image/video_dt.mp4" type="video/mp4" />
        </video>-->
        <video controls="controls" autoplay muted loop id="bg-video">
            <source src="/Images/video_dt.mp4" type="video/mp4" />
        </video>


        <div class="video-overlay header-text">
            <div class="caption">
                <h6>Hiệu suất mạnh mẽ</h6>
                <h2>Khẳng Định Thương Hiệu <em>THIẾT BỊ ĐIỆN TỬ</em></h2>
                <div class="main-button scroll-to-section">
                    @Html.ActionLink("Đăng Nhập","DangNhap","Dn")
                </div>
            </div>
        </div>
    </div>
   
    <footer>
        <div class="container">
            <div class="row">

                <div class="col-lg-12">
                    <p>
                        Copyright &copy; 2022 Training Studio

                        - Designed by <a rel="nofollow" href="https://www.facebook.com/kho.trai.1422" class="tm-text-link" target="_parent">Minh chiến</a>
                    </p>

                     <!--You shall support us a little via PayPal to info@templatemo.com--> 

                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="assets/js/jquery-2.1.0.min.js"></script>

    <!-- Bootstrap -->
    <script src="assets/js/popper.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>

    <!-- Plugins -->
    <script src="assets/js/scrollreveal.min.js"></script>
    <script src="assets/js/waypoints.min.js"></script>
    <script src="assets/js/jquery.counterup.min.js"></script>
    <script src="assets/js/imgfix.min.js"></script>
    <script src="assets/js/mixitup.js"></script>
    <script src="assets/js/accordions.js"></script>

    <!-- Global Init -->
    <script src="assets/js/custom.js"></script>

</body>

</html>