Ps18790_VoMinhChien_AsmGD2/demo/demo/Models/ShowSanPham.cs
namespace demo.Models
{
    public partial class ShowSanPham
    {
        public int MaSanPham { get; set; }
        public string HinhAnh { get; set; }
        public string TenSanPham { get; set; }
        public string GiaSanPham { get; set; }
        public bool? TinhTrang { get; set; }
        public int? MaTheLoai { get; set; }
        public string ThongTin { get; set; }
        public string Khac { get; set; }
        public bool? Isdelete { get; set; }

        public virtual TheLoai MaTheLoaiNavigation { get; set; }
        
       
    }
}

Ps18790_VoMinhChien_AsmGD2/demo/demo/Controllers/ShowGioHangController.cs
using demo.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace demo.Controllers
{
    public class ShowGioHangController : Controller
    {
        private readonly C4Context _context;

        public ShowGioHangController(C4Context context)
        {
            _context = context;
        }
        public SanPham Find(int id)
        {
            var a = _context.SanPham.Find(id);
            return a;
        }
        [Route("index")]

        public IActionResult Index()
        {
            var cart = SessionExtensions.GetobjectFromJson<List<Items>>(HttpContext.Session, "cart");
            ViewBag.cart = cart;

            if (cart != null)
            {
                ViewBag.total = cart.Sum(item => double.Parse(item.sp.GiaSanPham) * item.SoLuong);
            }


            return View();
        }
        private int isExist(int id)
        {
            List<Items> cart = SessionExtensions.GetobjectFromJson<List<Items>>(HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].sp.MaSanPham.Equals(id))
                {
                    return i;
                }  
            }
            return -1;
        }
        [Route("buy/{id}")]
        public IActionResult buy(int id)
        {
            if (SessionExtensions.GetobjectFromJson<List<Items>>(HttpContext.Session, "cart") == null)
            {
                List<Items> cart = new List<Items>();
                cart.Add(new Items
                {
                    sp = Find(id),
                    SoLuong = 1
                });
                SessionExtensions.SetobjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                List<Items> cart = SessionExtensions.
                                 GetobjectFromJson<List<Items>>(HttpContext.Session, "cart");
                int index = isExist(id);
                if (index != -1)
                {
                    cart[index].SoLuong++;
                }
                else
                {
                    cart.Add(new Items
                    {
                        sp = Find(id),
                        SoLuong = 1
                    });
                }
                SessionExtensions.SetobjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToAction("Index");

        }
        [Route("remove/{id}")]
        public IActionResult Remove(int id)
        {
            List<Items> cart = SessionExtensions.GetobjectFromJson<List<Items>>(HttpContext.Session, "cart");
            int index = isExist(id);
            cart.RemoveAt(index);
            SessionExtensions.SetobjectAsJson(HttpContext.Session,"cart", cart);
            return RedirectToAction("Index");
        }
    }
}

Ps18790_VoMinhChien_AsmGD2/demo/demo/Controllers/ShowSanPhamController.cs
using demo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace demo.Controllers
{
    public class ShowSanPhamController : Controller
    {
        private readonly C4Context context;

        public ShowSanPhamController(C4Context context)
        {
            this.context = context;
        }

        public async Task<IActionResult> Index(int MaTheLoai)
        {
            var sanPhamTheoMa = await context.SanPhams.Where(s => s.MaTheLoai == MaTheLoai).ToListAsync();

            ViewBag.SanPhams = sanPhamTheoMa;
            return View();
        }


        [Route("/{id}")]
        public async Task<IActionResult> Details(int id)
        {
            var currentProduct = await context.SanPhams.SingleAsync(p => p.MaSanPham == id  );
            

            ViewBag.CurrentProduct = currentProduct;
            return View();
        }


    }
}

Ps18790_VoMinhChien_AsmGD2/demo/demo/Views/ShowSanPham/Details.cshtml
@using demo.Models

@{
    Layout="_layout";
}
@{
    //ViewData["Title"] = "Privacy Policy";
    var currentProduct = ViewBag.currentProduct as SanPham;
}
<div style ="text-align:center">
    <a asp-controller="home" asp-action="index" class="btn btn-primary my-4">Trang chủ</a>

<h1>@currentProduct.TenSanPham</h1>
<img src="~/Images/@currentProduct.HinhAnh" width="300"/>
<div style="text-align:center;color:red">Giá Sản Phẩm :@currentProduct.GiaSanPham</div>
<div style="font-weight:bold; text-align:center"> Thông Tin:<br /> </div>
<div> @currentProduct.ThongTin</div>
<a asp-controller="ShowGioHang" asp-action="buy" asp-route-id="@currentProduct.MaSanPham" style="width:200px;height:50px;margin-bottom:20px" >Thêm Vào Giỏ <img src="~/Images/giohangmauden1.png"/> </a>
</div>

Ps18790_VoMinhChien_AsmGD2/demo/demo/Views/ShowSanPham/Index.cshtml
@using demo.Models

@{
    Layout = "_Layout";
    var sanphams = ViewBag.sanphams as List<SanPham>;
}

<style>
    .products {
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    }

    .anhsanpham {
        width: 80%;
        margin-left:30px;
    }

    .ttsp {
        /*background-color:red;*/
        text-decoration: none;
        border: 1px solid black;
    }
</style>
<div class ="products">
    @if(sanphams != null)
    {
        foreach(var product in sanphams)
        {
            <a class ="ttsp" asp-controller="ShowSanPham" asp-action="Details" asp-route-id="@product.MaSanPham">
                <img class='anhsanpham' src="~/Images/@product.HinhAnh" />
                <h3 style="text-align:center">@product.TenSanPham</h3>
                <div style="text-align:center">Giá : @product.GiaSanPham.ToString() đ</div>
               @* <img style="margin-left:40%" src="~/Images/giohangmauden.png">*@
            </a>
        }

           
           
        
    }
</div>